### ISSUE TITLE
Links úteis

### ISSUE THREAD

**Issue by dudecd3** [iagoggcarrazzoni/ex15-afnd2er#1]
Pessoal, pesquisando sobre a linguagem Latex, achei esses links que estão me ajudando muito. Compartilho com vocês para que todos sejamos igualmente capazes no projeto.

https://pt.wikibooks.org/wiki/Latex/T%C3%ADtulo

http://each.uspnet.usp.br/sarajane/wp-content/uploads/2016/10/manual-latex-1.pdf

http://sbi.iqsc.usp.br/files/Manual-SBI_LATEX_2013-.pdf

Peço que comentem o issue quando visualizarem, para que possamos fechá-lo quando a informação chegar a todos.

**Comment by Brenda100** [comment]
Certo! Obrigada!

**Comment by dudecd3** [comment]
Encontrei mais alguns: 

http://www.alessandroduarte.com.br/?page_id=288

http://www.fisica.ufjf.br/vwfme/comandoslatex.html
