### ISSUE TITLE
DIA

### ISSUE THREAD

**Issue by dudecd3** [iagoggcarrazzoni/ex15-afnd2er#3]
Pessoal, olhei o template do código e percebi que há uma forma de representar autômatos na linguagem Latex, mas creio que seja mais simples para nós utlizarmos o programa DIA para montar os grafos necessários e, posteriormente, inserí-los no artigo como imagem. Gostaria de saber qual a opinião de vocês , para decidirmos como faremos o trabalho.

**Comment by Brenda100** [comment]
Vou analisar o programa para trazer mais ideias. Mas acredito que seja mais fácil pelo que eu já vi até agora.

**Comment by dudecd3** [comment]
Pessoal, entendi a questão da representação do autômato. É extremamente simples e direto. Acho que é melhor utilizarmos a sintaxe da linguagem do que upar uma imagem.

**Comment by dudecd3** [comment]
Pessoal, estou utilizando a própria sintaxe da linguagem para construir os autômatos.

**Comment by iagocarrazzoni** [comment]
Eu acho que assim está bom, Couto

**Comment by dudecd3** [comment]
Já que resolvemos como vamos continuar, o issue cumpriu seu papel.
