### ISSUE TITLE
Uso do caractere '|'

### ISSUE THREAD

**Issue by dudecd3** [iagoggcarrazzoni/ex15-afnd2er#4]
Pessoal, tentei usar o caractere que está entre aspas no título do issue para representar o conectivo lógico 'OU', assim como utilizamos ao escrever um autômato no papel. Contudo, o compilador entende como '---', e é isso que está sendo escrito no lugar do caractere desejado. Alguém sabe como corrigir este problema?

**Comment by iagocarrazzoni** [comment]
Vou dar uma olhada. Em que parte está isso daí?

**Comment by dudecd3** [comment]
No autômato da seção sobre expressão regular e no texto abaixo dele.

**Comment by iagocarrazzoni** [comment]
Beleza, vou lá checar
