### ISSUE TITLE
Tipo de abordagem.

### ISSUE THREAD

**Issue by LuccaMacielM** [iagoggcarrazzoni/ex15-afnd2er#5]
Galera, vi um outro tipo de abordagem na explicação de transformação de AFND para AFD, segue o link:

https://www.youtube.com/watch?v=mCwQoM8KaZk .

A depender da nossa estratégia, o link demonstra um jeito interessante de resolução de AFND -> AFD, porém não tão voltado para a programação.

**Comment by iagocarrazzoni** [comment]
Boa, Lucca. Vou dar uma olhada
